### ISSUE TITLE
Writer.save fails on empty contents

### ISSUE THREAD

**Issue by agarwal** [janestreet/async_unix#5] opened 2015-10-17 21:25 UTC
I tried creating an empty file using `Writer.save`, but it fails. I can work around it by using any of several other methods, but curious why `save` doesn't work with empty `contents`. Is it intentional or is this a bug?

```
utop # Writer.save "foo.txt" ~contents:"";;
Exception:                                                                                                                              (src/monitor.ml.Error_
 ((exn                                                                                                                                  
   ("writer error"
    ((src/monitor.ml.Error_
      ((exn (Unix.Unix_error "Invalid argument" writev "")) (backtrace (""))
       (monitor
        (((name (id 118)) (here ()) (id 118) (has_seen_error true)
          (is_detached true) (kill_index 0))
         ((name block_on_async) (here ()) (id 115) (has_seen_error false)
          (is_detached true) (kill_index 0))))))
     ((id 9)
      (fd
       ((file_descr 46) (info foo.txtPlkeyr) (kind File)
        (supports_nonblock false) (have_set_nonblock false)
        (state (Open Empty))
        (watching ((read Not_watching) (write Not_watching)))
        (watching_has_changed false) (num_active_syscalls 1)
        (close_finished Empty)))
      (monitor
       (((name (id 117)) (here ()) (id 117) (has_seen_error true)
         (is_detached false) (kill_index 0))
        ((name block_on_async) (here ()) (id 115) (has_seen_error false)
         (is_detached true) (kill_index 0))))
      (inner_monitor
       (((name (id 118)) (here ()) (id 118) (has_seen_error true)
         (is_detached true) (kill_index 0))
        ((name block_on_async) (here ()) (id 115) (has_seen_error false)
         (is_detached true) (kill_index 0))))
      (background_writer_state Stopped_permanently) (syscall Per_cycle)
      (bytes_received 0) (bytes_written 0) (scheduled <opaque>)
      (scheduled_bytes 0) (buf <opaque>) (scheduled_back 0) (back 0)
      (flushes <opaque>) (close_state Open) (close_finished Empty)
      (close_started Empty) (producers_to_flush_at_close ())
      (flush_at_shutdown_elt (<opaque>)) (check_buffer_age ())
      (consumer_left Empty) (raise_when_consumer_leaves true)
      (open_flags (Full (Ok (rdwr))))))))
  (monitor
   (((name (id 117)) (here ()) (id 117) (has_seen_error true)
     (is_detached false) (kill_index 0))
    ((name block_on_async) (here ()) (id 115) (has_seen_error false)
     (is_detached true) (kill_index 0)))))).
```

**Comment by diml** [comment] 2015-10-19 09:18
That definitely looks like a bug, we'll look into it.

**Comment by solongordon** [comment] 2016-02-25 18:11
I'm seeing a very similar error if I write an empty string to stdout and a non-empty string to stderr.
```ocaml
open Async.Std

let () =
  print_string "";
  prerr_string "error";
  Core.Std.never_returns (Scheduler.go ())
```
Note this only errors out if the program's output is piped or redirected, e.g.
```
corebuild example.native
./example.native | cat
```

**Comment by diml** [comment] 2016-02-26 15:23
I can't manage to reproduce any of these errors, what version of async_unix are you using?

**Comment by solongordon** [comment] 2016-02-26 15:30
I'm using 113.00.00 on OS X. (I tried to test out 113.24.00 but was hitting some compilation issues.)

**Comment by diml** [comment] 2016-02-26 17:43
OK, I can reproduce this as well on OSX. I initially read the error wrong, I didn't notice it was the system call that returned `EINVAL` directly. Reading the OSX man page for writev it's indeed the case that you can't call writev with 0 iovectors. I'll try to get a fix for next release

**Comment by solongordon** [comment] 2016-02-26 18:08
Great! Happy to submit a PR if that would be helpful.

**Comment by bmillwood** [comment] 2017-07-31 18:34
I understand this is fixed in more recent versions.

**Closed by bmillwood** 2017-07-31 18:34 UTC
